###
POST http://localhost:3000/products
content-type: application/json

{
	"name": "Product 2",
	"detail": "Product 1 detail",
	"price": 100,
	"quantity": 10
}
###

###Get all products
GET http://localhost:3000/products
content-type: application/json
###

###Get products by id
GET http://localhost:3000/products/679ee4eac470455b80f6872f
content-type: application/json
###

###Update products by id
PUT http://localhost:3000/products/679ee4eac470455b80f6872f
content-type: application/json

{
	"quantity": 1000
}
###

###Delete products by id
Delete http://localhost:3000/products/679ee4eac470455b80f6872f
content-type: application/json
###
